Resources:
  artifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  codeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'
              - Action:
                - 's3:Get*'
                - 's3:Put*'
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${artifactStoreBucket}/*"

  build:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref 'RepositoryName'
      Source:
        Type: GITHUB
        Location: !Ref 'GithubRepositoryCloneUrl'
      Artifacts:
        Type: S3
        Location: !Ref 'artifactStoreBucket'
        NamespaceType: NONE
        Name: build-output.zip
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/ruby:2.3.1"
        ComputeType: BUILD_GENERAL1_SMALL
      ServiceRole: !Ref codeBuildRole

Parameters:
  GithubRepositoryCloneUrl:
    Type: String
    Default: https://github.com/km-aws-devops/standalone-build-servers-api-ruby.git

  RepositoryName:
    Type: String
    Default: standalone-build-servers-api-ruby

Outputs:
  BuildProjectName:
    Value: !Ref 'build'

